### PR TITLE
Change background color from black to white index.html

### PR DESCRIPTION
**Pull request by plan5**
This PR is meant to fix https://github.com/farooqkz/chooj/issues/36

On Nokia 8000 4G, this fixes the issue of unfocused messages in RoomView being unreadable due to black text on black background setting. Quick tests with Nokia 8110 showed no issues.

### CODE REVIEW

**Comment by farooqkz** [comment]
@plan5 Thank you for your contribution! I am gonna test this on my own device(Nokia 800 Tough) and invite people to test it to make sure it's fine.

**Comment by farooqkz** [comment]
I've tested on my device and there is a problem. The status bar is totally white and therefore the stuff in there cannot be seen. I have to investigate on this further. But I think it has to do something either with an entry in `manifest.webapp` or a `<meta>` in the index file.

**Comment by farooqkz** [comment]
The same problem exists in this PR of yours. You have mixed again.

**Comment by plan5** [comment]
This is weird. These commits were added when I created #93 it seems to me. 

As this PR turned out to be more of a workaround than a fix anyway, I'll close it.

**Pull request closed without merging**
