### PR TITLE
Fix for login issue

### PR DESCRIPTION
**Pull request by scttrgd**
remove 8448 from login POST
remove server from username field
close opened state on RoomsView

### CODE REVIEW

**Comment by farooqkz** [comment]
Hello. I am glad you are interested in contributing. Currently PRs should wait till I finish converting to TS.

P.S.: What KaiOS device have you got?

**Comment by scttrgd** [comment]
Ah my bad, didn't see that you were converting! I'm running a nokia 8110 4g.

**Comment by farooqkz** [comment]
> 

Not your bad :)

**Comment by farooqkz** [comment]
@scttrgd The typescript convert is almost complete! You can get started to rebase your PR :)

**Comment by farooqkz** [comment]
@scttrgd Since there was no response from you, I'm closing this PR soon.

**Pull request closed without merging**
